### ISSUE TITLE
Examples in /examples/ directory plus script to convert ckanext-scheming to json schema

### ISSUE THREAD

**Issue by rufuspollock** [datopian/jsv#13]
## Acceptance

* [ ] We have a couple of local examples (maybe in fixtures?) that we can use for demoing / trialling.
* [ ] we have a script for converting ckanext-scheming to json schema (and then to output)

## Tasks

* [ ] Push to `/examples/` files such as `data-package.json` and `data-resource.json` and other real-wolrd examples (if nothing confidential)
* [ ] Convert non-JSON Schema to JSON Schema NB: not really clear this should be here but no other obvious location atm.
  * [ ] Script [`ckanext-scheming`](https://github.com/ckan/ckanext-scheming) to JSON Schema 
* [ ] Add to examples
